### ISSUE TITLE
Use scala-steward?

### ISSUE THREAD

**Issue by takayahilton** [tototoshi/play-json4s#26]
**Description**
>Scala Steward is a bot that helps you keeping library dependencies and sbt plugins up-to-date.

https://github.com/fthomas/scala-steward#scala-steward

All you have to do is edit this [repos](https://github.com/scala-steward-org/repos/edit/master/repos-github.md) and send PR.

**Comment by tototoshi** [comment]
Thank you very much. I'm using it now. It's very useful.
